name: minecraftMod
author: Dein Name hier
main: org.example.Main
version: 1.0
api-version: 1.19
commands:
  helloworld:
    description: Sends chat message to player
    aliases:
      - hello
      - world
      - hw
softdepend:
  - Multiverse-Core
  - Vault